"""Add about_me column to User model

Revision ID: 368e68d26797
Revises: 69965d8b5835
Create Date: 2023-04-07 06:04:27.065507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368e68d26797'
down_revision = '69965d8b5835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
